config/routes.rb
Howto::Application.routes.draw do
  root to: redirect('/tasks')

  resources :tasks do
    resources :steps
  end

end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :description, :name, :task_id

  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name

  has_many :steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @task = Task.find(params[:task_id])
    @step = @task.steps.build
  end

  def create
    @task = Task.find(params[:task_id])
    @step = @task.steps.build(params[:step])

    @step.save
    redirect_to @task
  end


  def destroy
    @task = Task.find(params[:task_id])
    Step.destroy(params[:id])
    flash[:notice] = "Step has been deleted."
    redirect_to @task
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])

    @task.save
    flash[:notice] = "Your task was created!"
    redirect_to @task
  end

  def show
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |kind, message| %>
<div class="alert" id="<%= kind %>">
	<%= message %>
</div>
<% end %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/steps/new.html.erb
<h2>New Step</h2>

<%= form_for [@task, @step] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/tasks/index.html.erb
<h2>All Tasks</h2>

<%= link_to "New Task", new_task_path, :class => "btn btn-primary" %>

<ul>
	<% @tasks.each do |task| %>
	<li><%= link_to task.name, task %></li>
	<% end %>
</ul>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= form_for(@task) do |f| %>
<fieldset>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit :class => "btn btn-primary" %>
</fieldset>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<ol>
	<% @task.steps.each do |step| %>
	<li><%= link_to step.name, [@task, step] %>
		<%= link_to("Delete", [@task, step], :method => :delete, :confirm => "Are you sure you want to delete this step?", :class => "btn btn-danger btn-small") %>
	</li>
	<% end %>
</ol>
<p><%= link_to "Add a Step", new_task_step_path(@task), :class => "btn btn-primary" %></p>
<p><%= link_to "All Tasks", tasks_path %></p>